### ISSUE TITLE
Making it easier to sort through users based on access?

### ISSUE THREAD

**Issue by tnguyen21** [sharingexcess/rescue#111]
As we have more of the distro team and drivers being onboarded on the app, I can imagine it'll be useful to have filters on the Manage Users page along the lines of "View all users with no access", "View only admins", etc

This isn't a huge deal now since we only have a handful of people currently registered on the app, but perhaps something useful in the future as we on-board more drivers.

**Comment by ryanmchenry2** [comment]
Definitely a good thought. As of now, we are only storing the permission level within the auth data of a user, which is only accessible from requests to a cloud function. So in order to create that functionality, we would have to send out a cloud function request for each user in the list on render (instead of only for a single user when their page is viewed), which is definitely resource intensive. With that in mind, I'd table this for now. If we decide this is important in the future, I'd advocate for adding the admin/basic access data to the users table in Firestore as well so that we can more easily access that info. That does mean managing duplicate data though, which needs to be done carefully.
