### ISSUE TITLE
Bug: Delivery Report submits as 0% of food delivered

### ISSUE THREAD

**Issue by lukeshinnn** [sharingexcess/rescue#395]
### Describe the bug

When drivers go to submit the delivery report, they will move the toggle to indicate that 100% of pounds have been delivered to that stop.
After submitting the delivery report, the delivery report will automatically change to say 0% of pounds have been delivered. (This has happened to multiple drivers)

### Steps to reproduce

1. Create a new rescue and assign yourself as a driver.
2. Start the rescue and complete the pickup report.
3. Try to complete the delivery report (submit that 100% of food has been delivered)
4. After the delivery report has been submitted, check submitted route data to see if delivery report still reflects that all food has been delivered

### Affected services

rescue

### Platforms

Desktop, Mobile

### Browsers

Chrome, Safari

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by armandoparra13** [comment]
I tried to reproduce the bug, and this is what I found:

I was unable to reproduce the bug with a single delivery, but this happened with a multiple deliveries ( I know that there shouldn't usually be multiple deliveries, but I thought I'd check it since some people still have multiple deliveries). For the last delivery, I chose 100% of the load but when looking at the routes, 0 lbs. were delivered.

![image](https://user-images.githubusercontent.com/78700199/149569257-3a7b226e-14b6-4e42-a0e8-9343ee6d8666.png)
![image](https://user-images.githubusercontent.com/78700199/149569296-eb50492e-ccd7-489b-b05f-8cc346bc6b6e.png)
